# Generated by Django 6.0.6 on 2026-06-21 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="character",
            options={"ordering": ["api_id"]},
        ),
    ]
